#@data/values-schema

---
name: "gimie-api"
version: ""
#@schema/validation min_len=1
namespace: "gimie"
replicas: 1
#@schema/validation min_len=1
image: "ghcr.io/sdsc-ordes/gimie-api:latest"
tokens:
  github: ""
  gitlab: ""
