#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("common.lib.star", "resourceLabels")
#@ v = data.values

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: #@ v.name + "-tokens"
  labels: #@ resourceLabels(v)
data:
  GITHUB_TOKEN: #@ base64.encode(v.tokens.github)
  GITLAB_TOKEN: #@ base64.encode(v.tokens.gitlab)
